// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbefwlhezngkwsxybrsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZWZ3bGhlem5na3dzeHlicnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Mzc0OTksImV4cCI6MjA2NDExMzQ5OX0.Rs_RFvKYsqCIA0JIMZkGGw7QduyMgEhQ4CDdyA3aIxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);